homepage: "https://python-pillow.org/"
language: c++
primary_contact: "zach@in8-solutions.com"
sanitizers:
 - address
 - undefined
architectures:
 - x86_64
fuzzing_engines:
  - libfuzzer
  - honggfuzz
